name: Build LaTeX document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: ./book.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: book.pdf

    - name: Commit and push PDF
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add the book.pdf
        git commit -m "Add compiled PDF"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}